"""horario_reserva reserva

Revision ID: ab0e135ec62b
Revises: a6b3b6ee4413
Create Date: 2026-02-04 15:53:23.434808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab0e135ec62b'
down_revision: Union[str, Sequence[str], None] = 'a6b3b6ee4413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservas', sa.Column('horario_reserva', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservas', 'horario_reserva')
    # ### end Alembic commands ###
